#!/usr/bin/env bash
set -ex
# --notebook-dir
ROOT="$(git rev-parse --show-toplevel)"
exec poetry run jupyter notebook \
  --no-browser\
  --ip='0.0.0.0'\
  --NotebookApp.allow_origin='*'\
  --notebook-dir=$ROOT/docs/examples
