#!/usr/bin/env bash
set -ex
rm -rf docs/_build/
poetry run sphinx-build docs docs/_build -b doctest
poetry run pip install sphinx-autobuild
exec poetry run sphinx-autobuild docs docs/_build --watch src/otf  -b html --watch doc --host 0.0.0.0
