name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - run: pip install tox
    - name: Run tests and collect coverage
      run: tox -- --cov-report term-missing:skip-covered --cov-report xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
