name: publish to PyPI
on: [push]
jobs:
  pypi:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - run: pip install poetry>=1.1.13
    - run: poetry build
    - uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        repository_url: https://pypi.org/legacy/
