# .github/workflows/test-pypi.yml
name: TestPyPI
on:
  push:
    branches:
      - main
jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - run: pip install poetry>=1.1.13
    - run: >-
        poetry version "$(poetry version -s).dev$(date +%s)"
    - run: poetry build
    - uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
